using Rayforge.Core.Environment.Abstractions;
using System;
using System.Collections.Generic;
using System.Runtime.ConstrainedExecution;
using UnityEngine;

namespace Rayforge.Core.Environment.Spatial
{
    /// <summary>
    /// A high-performance base class for managing the lifecycle and storage of spatial objects.
    /// Handles dictionary-based storage, automated GameObject instantiation, hierarchy management, 
    /// and dirty state tracking.
    /// </summary>
    /// <typeparam name="TKey">The type used for spatial indexing (e.g., Vector3Int).</typeparam>
    /// <typeparam name="TValue">The type of spatial object, must be a MonoBehaviour and implement ISpatialEntry.</typeparam>
    public abstract class SpatialRegistry<TKey, TValue> : IDisposable
        where TValue : ISpatialEntry
    {
        #region Data Structures
        /// <summary> Internal storage for spatial objects. Encapsulated to ensure dirty-flag integrity. </summary>
        private readonly Dictionary<TKey, TValue> _storage = new Dictionary<TKey, TValue>();

        /// <summary> Parent transform for instantiated GameObjects. </summary>
        private Transform _container;

        /// <summary> Tracks if the container was created by this registry to allow auto-cleanup. </summary>
        private bool _isAutoGeneratedContainer = false;

        /// <summary> Flag indicating if the collection composition (addition/removal) has changed. </summary>
        protected bool _globalDirty = false;

        /// <summary> Provides read-only access to all currently registered entries. </summary>
        public Dictionary<TKey, TValue>.ValueCollection AllEntries => _storage.Values;

        /// <summary> 
        /// The unique identification string of this registry instance.
        /// Useful for logging and identifying the container in the hierarchy.
        /// </summary>
        public string RegistryName { get; }
        #endregion

        /// <summary>
        /// Initializes the registry. 
        /// </summary>
        /// <param name="container">Optional parent transform. If null, a default one is created in Play Mode.</param>
        /// <param name="defaultName">The name for the auto-generated container.</param>
        protected SpatialRegistry(Transform container = null, string defaultName = "SpatialRegistry_Container")
        {
            if (container == null && Application.isPlaying)
            {
                var go = new GameObject(defaultName);

                RegistryName = $"{defaultName}_{go.GetInstanceID()}";
                go.name = RegistryName;

                _container = go.transform;

                _isAutoGeneratedContainer = true;
            }
            else
            {
                _container = container;
            }
        }

        #region Lifecycle Management
        /// <summary>
        /// The master factory method. Retrieves an existing entry or creates, parents, and registers a new one.
        /// </summary>
        /// <param name="key">The spatial key for indexing.</param>
        /// <param name="name">The name for the new GameObject.</param>
        /// <param name="position">The initial world position.</param>
        /// <param name="factory">Factory method for initialization.</param>
        /// <returns>The existing or newly created entry.</returns>
        protected TValue GetOrCreate(TKey key, string name, Vector3 position, System.Func<GameObject, TKey, TValue> factory)
        {
            if (_storage.TryGetValue(key, out TValue existing))
            {
                if (existing != null && existing.gameObject != null) return existing;
                _storage.Remove(key);
            }

            GameObject go = new GameObject(name);
            if (_container != null) go.transform.SetParent(_container);
            go.transform.position = position;

            TValue entry = factory.Invoke(go, key);

            if (entry == null)
            {
                if (Application.isPlaying) UnityEngine.Object.Destroy(go);
                else UnityEngine.Object.DestroyImmediate(go);
                throw new System.Exception($"Registry {GetType().Name}: Factory lambda returned null for key {key}.");
            }

            _storage[key] = entry;
            _globalDirty = true;
            return entry;
        }

        /// <summary>
        /// Attempts to retrieve an entry by its spatial key.
        /// Returns true if the entry exists, otherwise false.
        /// </summary>
        public bool TryGetEntry(TKey key, out TValue value)
        {
            return _storage.TryGetValue(key, out value);
        }

        /// <summary>
        /// Safely destroys the GameObject associated with the key and removes it from storage.
        /// Also triggers auto-cleanup of the container if applicable.
        /// </summary>
        public virtual void RemoveAndDestroy(TKey key)
        {
            if (_storage.Remove(key, out TValue value))
            {
                if (value != null && value.gameObject != null)
                {
                    if (Application.isPlaying) UnityEngine.Object.Destroy(value.gameObject);
                    else UnityEngine.Object.DestroyImmediate(value.gameObject);
                }

                _globalDirty = true;
                TryCleanupContainer();
            }
        }

        /// <summary>
        /// English: Disposes the registry and all its managed chunks.
        /// Triggers the abstract OnDispose logic in each chunk implementation.
        /// </summary>
        public virtual void Dispose() => Clear();

        /// <summary>
        /// Clears all entries, destroys their associated GameObjects, and removes the auto-generated container.
        /// </summary>
        public virtual void Clear()
        {
            // Copy keys to avoid modification errors during iteration
            List<TKey> keys = new List<TKey>(_storage.Keys);
            foreach (var key in keys)
                RemoveAndDestroy(key);

            _storage.Clear();
            _globalDirty = true;

            TryCleanupContainer();
        }

        /// <summary>
        /// Destroys the container if it was auto-generated and has no remaining children.
        /// </summary>
        private void TryCleanupContainer()
        {
            if (_isAutoGeneratedContainer && _container != null && _container.childCount == 0)
            {
                if (Application.isPlaying) UnityEngine.Object.Destroy(_container.gameObject);
                else UnityEngine.Object.DestroyImmediate(_container.gameObject);

                _container = null;
                _isAutoGeneratedContainer = false;
            }
        }
        #endregion

        #region State Management
        /// <summary>
        /// Determines if any entry is dirty or if the collection itself has changed.
        /// </summary>
        public bool NeedsUpdate()
        {
            if (_globalDirty) return true;
            foreach (var entry in _storage.Values)
                if (entry != null && entry.IsDirty) return true;
            return false;
        }

        /// <summary>
        /// Resets all internal and entry-level dirty flags after a synchronization cycle.
        /// </summary>
        public void ResetDirtyFlags()
        {
            _globalDirty = false;
            foreach (var entry in _storage.Values)
                if (entry != null) entry.ClearDirty();
        }
        #endregion
    }
}
